### ISSUE TITLE
1300元的差距，值得吗

### ISSUE THREAD

**Issue by Pinkie-Pie-173** [Sha1rholder/Sound-Library#1]
飞傲jt1和dt700prox，我本来想狠下心购入700prox的，但是多看几遍发现您是把700prox卖了换jt1.。。。。这下真的不知道该买哪个了，700prox的声音值那1300元的差距吗

**Comment by Sha1rholder** [comment]
绝大部分人包括发烧友，盲听是根本没法分辨这两个耳机谁声音更好的。但是有以下两点你可以参考下：

1. 你如果买了dt700prox不满意，你自己可能会先质疑自己的耳朵（我是不是木耳？我听音观是不是“不正”）；而买了飞傲JT1不满意的话，会先质疑推荐者的耳朵 ~~以及是不是收了厂商的钱~~……
2. 你如果买了dt700prox，说“感觉不如beats”，绝大部分发烧友都会讪笑你木耳；你如果买了飞傲JT1，说类似评价，多数发烧友则会说“哈哈果然飞傲也就这水平了，国产耳机就是不行，还请水军”

这就是品牌效应

换个问题：你买鼠标会选择罗技GPW3还是VGN蜻蜓F1？

Close了，但是如果还有问题欢迎继续留言
